### PR TITLE
Revert "Removed useless casts for default timestamps"

### PR DESCRIPTION
**Pull request by MrPunyapal**
Reverts pinkary-project/pinkary.com#731
Arch tests are failing.

### CODE REVIEW

**Comment by siarheipashkevich** [comment]
@MrPunyapal I think we can fix tests but not PR. Because it is the default behavior of the Laravel.

**Comment by siarheipashkevich** [comment]
@MrPunyapal I like the second option, because Laravel automatically casts the `created_at`, `updated_at` and `deleted_at` to datetime

**Comment by MrPunyapal** [comment]
fix: https://github.com/pinkary-project/pinkary.com/pull/739

**Comment by MrPunyapal** [comment]
> @MrPunyapal I like the second option, because Laravel automatically casts the `created_at`, `updated_at` and `deleted_at` to datetime

done, we don't have soft delete so I'm skipping `deleted_at` for now!
https://github.com/pinkary-project/pinkary.com/pull/739

**Pull request closed without merging**
