### PR TITLE
Add open graph card preview page

### PR DESCRIPTION
**Pull request by caendesilva**
Adds an open graph card [preview page](https://pinkary.com/opengraph-validator) like I talked about on [Twitter](https://x.com/MrPunyapal/status/1853422899404931415).
 
 
image

I tried to make this initial version as minimal as possible, but later on it could support things like HTML input, and actual validation.

The goal was to create a more modern version of the abandoned Twitter card validator.

image

### CODE REVIEW

**Comment by MrPunyapal** [comment]
Looks nice!

Something that is missing what Livewire and Alpine touch. 

It would be awesome if we could make it livewire way if not I would love to refactor it in the future!

**Comment by caendesilva** [comment]
> Looks nice!
> 
> Something that is missing what Livewire and Alpine touch.
> 
> It would be awesome if we could make it livewire way if not I would love to refactor it in the future!

Okay cool! I'll gladly refactor to Livewire/Alpine tomorrow unless you want to do it yourself. I wanted to make this PR as small as possible from the start so I could get your feedback on the feature before complicating it.

**Comment by MrPunyapal** [comment]
Okay! Let's wait for @nunomaduro's feedback 👌

**Comment by nunomaduro** [comment]
this feels outside of the scope of pinkary

**Pull request closed without merging**
