### PR TITLE
feat: renaming link "Description" to "Title"

### PR DESCRIPTION
**Pull request by aagjalpankaj**
- feat: ui - renamed link description to title
- ~~refactor: db - rename field `links.description` to `links.title` [pending]~~
- ~~refactor: code - rename code level occurrences of `links.description` to `links.title` [pending]~~

### CODE REVIEW

**Comment by aagjalpankaj** [comment]
@nunomaduro / @MrPunyapal - Does this change make sense? If yes, I can proceed refactoring db & code level occurrences.

**Comment by MrPunyapal** [comment]
One thing unrelated to things needs to be in separate PRs.

**Comment by aagjalpankaj** [comment]
@nunomaduro / @MrPunyapal as suggested keeping only UI change in this MR. I will create separate MR for refactoring (db & code) for this change.

This MR is ready to review & merge.

**Comment by nunomaduro** [comment]
No plans for this.

**Pull request closed without merging**
